### ISSUE TITLE
SampleScene appears empty?

### ISSUE THREAD

**Issue by andybak** [tertle/MeshDemo#2]
Aside from the default camera and light that is.

**Comment by castana1962** [comment]
Hi andyback
You see the Scene empty but if You play the Unity Editor, you will see several cubes flying in the scene
Hope this help !!!
Regards
Alejandro

**Comment by andybak** [comment]
Wow. I was thrown by the fact that there were no custom components in the scene whatsoever. Didn't even occur to me to press play.

What is this witchcraft!? ;-)
